title:  Terraform Input Variables
description:  Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Name for the compartment MUST be unique across all compartments in your tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${project_tag}

  
  - title: "1 Create security compartment"
    variables:
      - ${security_compartment_name}
      - ${security_compartment_description}
      - ${security_enable_delete}

  - title: "2 Create monitoring compartment"
    variables:
      - ${monitoring_compartment_name}
      - ${monitoring_compartment_description}
      - ${monitoring_enable_delete}  

  - title: "3 Create network compartment"
    variables:
      - ${network_compartment_name}
      - ${network_compartment_description}
      - ${network_enable_delete}         

  - title: "4 Create nonprodhub compartment"
    variables:
      - ${nonprodhub_compartment_name}
      - ${nonprodhub_compartment_description}
      - ${nonprodhub_enable_delete}    

  - title: "5 Create nonprod compartment"
    variables:
      - ${nonprod_compartment_name}
      - ${nonprod_compartment_description}
      - ${nonprod_enable_delete}    
      - ${nonprod_project_tag}  

  - title: "5.1 Create nonprod/nonprod_app sub-compartments"
    variables:
      - ${nonprod_app_compartment_name}
      - ${nonprod_app_compartment_description}
      - ${nonprod_app_enable_delete}
      - ${nonprod_app_project_tag}



  - title: "5.2 Create nonprod/nonprod_db sub-compartments"
    variables:
      - ${nonprod_db_compartment_name}
      - ${nonprod_db_compartment_description}
      - ${nonprod_db_enable_delete}
      - ${nonprod_db_project_tag}


#####################################
# Common Compartment
#####################################
variables:

  tenancy_ocid:
    visible: true
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    title: Region
    description: Region

  compartment_ocid:
    visible: true
    title: Provide the compartment_ocid for deployment
    description: Under this compartment all the resouces will be deployed

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 1 Create security compartment

  security_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_security"
    title: "compartment name"
    description: "Provide compartment Name"
   
  security_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to security"
    title: "compartment description"
    description: "Provide compartment description."

  security_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"

  ### 2 Create monitoring compartment

  monitoring_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_monitoring"
    title: "compartment name"
    description: "Provide compartment Name"
   
  monitoring_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to monitoring"
    title: "compartment description"
    description: "Provide compartment description."

  monitoring_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"


  ### 3 Create network compartment

  network_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_network"
    title: "compartment name"
    description: "Provide compartment Name"
   
  network_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to network"
    title: "compartment description"
    description: "Provide compartment description."

  network_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
           
### 4 Create nonprodhub compartment

  nonprodhub_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_nonprod_hub"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprodhub_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod_hub"
    title: "compartment description"
    description: "Provide compartment description."  

  nonprodhub_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  

### 5 Create nonprod compartment

  nonprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_nonprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod"
    title: "compartment description"
    description: "Provide compartment description."

  nonprod_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  nonprod_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 5.1 Create nonprod/nonprod_app sub-compartments

  nonprod_app_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_nonprod_app"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprod_app_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod_dev"
    title: "compartment description"
    description: "Provide compartment description."

  nonprod_app_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  nonprod_app_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 5.2 Create nonprod/nonprod_db sub-compartments

  nonprod_db_compartment_name:
    type: string
    required: true
    visible: true
    default: "oci_nonprod_db"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprod_db_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod_db"
    title: "compartment description"
    description: "Provide compartment description."

  nonprod_db_enable_delete:
    type: bool
    visible: true
    default: true
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  nonprod_db_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false
 