tenancy_ocid                      = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
compartment_ocid                  = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
region                            = "us-ashburn-1"
source_database_connection_ocid   = "ocid1."
target_database_connection_ocid   = "ocid1.."
test_key_ocid                     = "ocid2.."
test_vault_ocid                   = "ocid3.."
