title: Devops Code Repository
description: Devops Code Repository
schemaVersion: 1.1.0
version: "11072023"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Select Compartment"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${repo_name}
      - ${default_branch}
      - ${description}
      - ${repository_type}
      - ${project_name}
      - ${notification_topic}
      
variables:

#####################################
# Common Compartment
#####################################

  compartment_ocid:
    type: string
    visible: true
    title: Select the Compartment to deploy resources
    default : ""
    description: Choose the Compartment where to deploy the resources

  tenancy_ocid:
    visible: true
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    required: true
    title: Provide the Region
    description: Provide the Region
    default: "us-ashburn-1"

  repo_name:
    type: string
    visible: true
    required: true
    title: Repository Name
    description: Provide the name for the Repository
    default: "repositoryName"

  default_branch:
    type: string
    visible: true
    required: true
    title: Branch of Repository
    description: "The default branch of the repository"
    default: "defaultBranch"
  
  description:
    type: string
    visible: true
    required: true
    title: "Details of the repository"
    description: "Details of the repository"
    default: "description"

  repository_type:
    type: string
    visible: true
    required: true
    title: Repository Type
    description: "Type of repository"
    default: "HOSTED"
  
  project_name:
    type: string
    visible: true
    required: true
    title: Project Name
    description: "Provide the Project name "
    default: "project"


  notification_topic:
    type: string
    visible: true
    required: true
    title: Notification Topic Name
    description: "Provide name for Notification Topic"
    default: "test_topic_repo"
