title: KMS Vault Key Management System
description: Stores and manages master encryption keys and secrets for secure access to resources.
schemaVersion: 1.1.0
version: "25012022"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "OCI Vault Key Management System"
    variables:
      - ${oci_security_compartment_name}
      - ${oci_security_compartment_id_in_subtree}
      - ${tenancy_ocid}
      - ${project_tag}
      - ${vault_display_name}
      - ${vault_type}
      - ${region}

variables:

####################################
#  Compartment
####################################

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false
  
  security_compartment_name:
    type: string
    title: "Compartment Name"
    default: ""
    description: "Provide Compartment name"
    visible: true
    required: true

  security_compartment_id_in_subtree:
    type: bool
    title: "Compartment ID in Subtree"
    default: true
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  tenancy_ocid:
    visible: true
    title: tenancy ocid
    description: tenancy ocid

  region:
    visible: true
    title: Region
    description: Region
    
  vault_display_name:
    type: string
    required: true
    visible: true
    default: "OCI-LZ-KMS-VAULT"
    title: "The display name of KMS Vault."
    description: "It does not have to be unique, and it is changeable."

  vault_type:
    type: string
    required: true
    visible: true
    default: "VIRTUAL_PRIVATE"
    title: "Type of the Vault Key"
    description: "Whether or not the vault is a virtual private vault. It has different options and pricing"
  
  