   tenancy_ocid             = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
   region                   = "us-ashburn-1"
   hostname_label           = "hostnameLabel"
   ip_address               = "10.97.7.2"
   availability_domain      = "PMlX:US-ASHBURN-AD-1"
   db_compartment_name      =  "oci_nonprod_db" 
   network_compartment_name = "oci_network" 
   subnet_display_name      =  "dbtst_subnet" 
