tenancy_ocid                              = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
compartment_name                          = "oci_nonprod_db"
region                                    = "us-ashburn-1"
cloud_exadata_infrastructure_ocid         = "ocid1.."
cloud_auto_vm_cluster_subnet_ocid         = "ocid12.."