title:  Terraform Input Variables
description:  Terraform Input Variables
schemaVersion: 1.1.0
version: "03052023"

#####################################

# Variable Groupings

#####################################

groupings:

  - title: "ATP Configuration"
    variables:
      - ${database_db_name}
      - ${database_display_name}
      - ${autonomous_database_customer_contacts_email}
      - ${database_db_workload}
      - ${database_db_version}
      - ${database_cpu_core_count}
      - ${autonomous_database_is_dedicated}
      - ${autonomous_container_database_ocid}
      - ${autonomous_database_is_auto_scaling_enabled}
      - ${autonomous_database_is_auto_scaling_for_storage_enabled}
      - ${autonomous_database_is_mtls_connection_required}
      - ${database_data_storage_size_in_tbs}
      - ${database_admin_password}
      - ${database_license_model}
      - ${database_operations_insights_status}
      - ${database_permission_level}
      - ${create_private_database}
      - ${vcn_compartment_ocid}
      - ${vcn_ocid}
      - ${subnet_ocid}
      - ${nsg_ocid}
      - ${autonomous_database_source}

  - title: "Select the Target Compartment"
    variables:
      - ${compartment_id_in_subtree}
      - ${compartment_name}
      - ${network_compartment_id_in_subtree}
      - ${network_compartment_name1
      - ${tenancy_ocid}
      - ${region}

variables:

#####################################

# Common Compartment

#####################################
  compartment_ocid:
    type: oci:identity:compartment:id
    visible: true
    title: Select the Compartment to deploy resources
    description: Choose the Compartment where to deploy the resources

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: false
    title: Region
    description: Region


#####################################

  # Atonomous Database Configuration

#####################################

  database_db_name:
    type: string
    required: false
    visible: true
    default: "ociadb"
    title: "Database Name"
    description: "Provide Database Name"
   
  database_display_name:
    type: string
    required: false
    visible: true
    default: "oci_adb"
    title: "Database Display Name"
    description: "Provide Database Display Name."
    
  autonomous_database_customer_contacts_email:
    type: string
    required: true
    visible: true
    default: ""
    title: "Provide Shared Email Inbox for Autonomous Database."
    description: "Provide Email-ID for Customer Contact"

  database_db_workload:
    type: enum
    required: false
    visible: true
    default: "OLTP"
    title: "Database workload type"
    description: "Choose Database workload."
    enum:
          - "OLTP"
          - "DW"
          - "AJD"
          - "APEX"

  database_db_version:
    type: string
    required: false
    visible: true
    default: "19c"
    title: "Database Version"
    description: "Database Version."

  database_cpu_core_count:
     type: number
     required: false
     visible: true
     minimum: 1
     maximum: 128
     multipleOf: 1
     default: 1
     title: "Database CPU Core Count"
     description: "Choose Database CPU Core Count."
    
  autonomous_database_is_dedicated:
    type: boolean
    visible: true
    title: Create Dedicated Autonomous Database ?
    description: If this is set to true, Autonomous Database will be created on dedicated infrastructure, if set to false Autonomous Database will be created on Shared infrastructure
    default: false
    required: false

  autonomous_container_database_ocid:
    type: string
    visible: ${autonomous_database_is_dedicated}
    title: Autonomous Container Database OCID
    description: Provide Autonomous Container Database OCID
    default: ""
    required: true
  
  autonomous_database_is_auto_scaling_enabled:
    type: boolean
    visible: true
    title: Enable auto scaling for OCPU ?
    description: Specify whether to enable auto scaling, if unchecked no auto scalling will take place 
    default: true
    required: true

  autonomous_database_is_mtls_connection_required:
    type: boolean
    visible: true
    title: Enable MTLS Connection ?
    description: Specify whether to enable MTLS Connection
    default: true
    required: true

  autonomous_database_is_auto_scaling_for_storage_enabled:
    type: boolean
    visible: true
    title: Enable auto scaling for storage ?
    description: Specify whether to enable auto scaling, if unchecked no auto scaling will take place 
    default: true
    required: true

  database_data_storage_size_in_tbs:
    type: number
    required: false
    visible: true
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Database Data Storage Size (TB)"
    description: "Choose Database Data Storage Size in terabytes."

  database_admin_password:
    type: password
    required: true
    visible: true
    title: "Database Password"
    description: "Database Password for ADMIN user."
    minLength: 12
    maxLength: 30
    pattern: ^[A-Za-z][A-Za-z0-9_#\$]+$ 

  database_license_model:
    type: enum
    required: false
    visible: true
    default: "BRING_YOUR_OWN_LICENSE"
    title: "Database License Model"
    description: "Choose Database License Model."
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"
  
  database_operations_insights_status:
    type: enum
    required: false
    visible: true
    default: "NOT_ENABLED"
    title: "Database operations insights status"
    description: "Choose Database operations insights status"
    enum:
      - "ENABLED"
      - "NOT_ENABLED"


  database_permission_level:
    type: enum
    required: false
    visible: true
    default: "UNRESTRICTED"
    title: "Database permission_level"
    description: "Choose Database permission_level"
    enum:
      - "RESTRICTED"
      - "UNRESTRICTED"

  autonomous_database_source:
    type: string
    visible: false
    title: Autonomous Database Source ?
    default: NONE
    required: false

#####################################
# Network Configuration
#####################################

  create_private_database:
    type: boolean
    required: true
    visible: true
    default: true
    title: Create Private database?
    description: Choose whether to create private autonomous database

  vcn_compartment_ocid:
    type: oci:identity:compartment:id
    visible: ${create_private_database}
    title: Select the VCN Compartment
    description: Choose the Compartment of VCN
    required: ${create_private_database}

  vcn_ocid:
    type: oci:core:vcn:id
    visible: ${create_private_database}
    title: Select the VCN
    description: Choose the VCN
    dependsOn: 
      compartmentId: ${vcn_compartment_ocid}
    required: ${create_private_database}

  nsg_ocid:
    type: oci:core:nsg:id
    visible: ${create_private_database}
    title: Select the Network Security Group
    description: Select the Network Security Group (Optional)
    dependsOn:
      compartmentId: ${vcn_compartment_ocid}
      vcnId: ${vcn_ocid}
    required: false
    default: ""
  
  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true