title: OCI Core Instance instance 
description: OCI Core Instance instance 
schemaVersion: 1.1.0
version: "25012022"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Select Compartment and Subnet"
    variables:
      - ${region}
      - ${tenancy_ocid}
      - ${compartment_ocid}
      - ${project_tag}
     
      - ${subnet_ocid}

  - title: "OCI Core Instance Configuration"
    variables:

      - ${vm_display_name}    
      - ${are_all_plugins_disabled}
      - ${is_management_disabled}
      - ${is_monitoring_disabled}

      - ${desired_state1}
      - ${name1}
      - ${desired_state2}
      - ${name2}
      - ${desired_state3}
      - ${name3}
      - ${desired_state4}
      - ${name4}
      - ${desired_state5}
      - ${name5}
      - ${desired_state6}
      - ${name6}
      - ${desired_state7}
      - ${name7      
      - ${assign_public_ip}
      - ${vnic_hostname}
      - ${fault_domain}
      - ${boot_volume_type}
      - ${firmware}
      - ${network_type}
      - ${remote_data_volume_type}
      - ${ssh_authorized_keys}
      - ${vm_shape}
      - ${memory_in_gbs}
      - ${ocpu_count}
     

variables:
### Common Compartment 

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Enter Tenancy OCID

  region:
    visible: true
    title: Region
    description: Enter Region
    default: "us-ashburn-1"
    
  compartment_ocid:
    type: oci:identity:compartment:id
    visible: true
    title: Select the Compartment to deploy resources
    description: Choose the Compartment where to deploy the resources

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


 
### VM  Configuration 

  vm_display_name:
    type: string
    required: true
    visible: true
    default: "instance"
    title: Vm display name
    description: vm display name

  are_all_plugins_disabled:
    type: boolean
    required: false
    visible: true
    title: Are all plugins disabled?
    description: Specify whether to enable object event, if unchecked no object event created
  
  is_management_disabled:
    type: boolean
    required: false
    visible: true
    title: Is management disabled?
    description: Specify whether management is disabled.
 
  is_monitoring_disabled:
    type: boolean
    required: false
    visible: true
    title: Is monitoring disabled?
    description: Specify whether to enable object event, if unchecked no object event created

  desired_state1:
    type: string
    required: false
    visible: true
    title: Desired State1
    default: DISABLED

  name1:
    type: string
    required: false
    visible: true
    title: Scans the instance for security vulnerabilities.
    default : "Vulnerability Scanning"

  desired_state2:
    type: string
    required: false
    visible: true
    title: Desired State2
    default: ENABLED

  name2:
    type: string
    required: false
    visible: true
    title: Manages updates and patches for the operating system environment on the instance.
    default : "OS Management Service Agent"

  desired_state3:
    type: string
    required: false
    visible: true
    title: Desired State3
    default: DISABLED

  name3:
    type: string
    required: false
    visible: true
    title: "Collects data from resources such as OSs, applications, and infrastructure resources for OCI services that are integrated with Management Agent. Data can include observability, log, configuration, capacity, and health data."
    default : "Management Agent"

  desired_state4:
    type: string
    required: false
    visible: true
    title: Desired State4
    default: ENABLED

  name4:
    type: string
    required: false
    visible: true
    title: "Ingests custom logs into the Logging service."
    default : "Custom Logs Monitoring"

  desired_state5:
    type: string
    required: false
    visible: true
    title: Desired State5
    default: ENABLED

  name5:
    type: string
    required: false
    visible: true
    title: "Runs scripts within the instance to remotely configure, manage, and troubleshoot the instance."  
    default : "Compute Instance Run Command"

  desired_state6:
    type: string
    required: false
    visible: true
    title: Desired State6
    default: ENABLED

  name6:
    type: string
    required: false
    visible: true
    title: "Emits metrics about the instance's health, capacity, and performance."  
    default : "Compute Instance Monitoring"

  desired_state7:
    type: string
    required: false
    visible: true
    title: Desired State7
    default: DISABLED

  name7:
    type: string
    required: false
    visible: true
    title: Configures block volume sessions within the instance.  
    default : "Block Volume Management"

  
  assign_public_ip:
    type: boolean
    required: false
    visible: true
    title: Enter true for Public IP and false for Private IP for the VM
    default: "false"

  vnic_hostname:
    type: string
    required: true
    visible: true
    default: "oicagent"
    title: VNIC hostname
    description: Select VNIC hostname for VM

  fault_domain:
    type: string
    required: true
    visible: true
    default: "FAULT-DOMAIN-1"
    title: Fault Domain
    description: Select Fault Domain

  boot_volume_type:
    type: enum
    required: false
    visible: true
    default: "PARAVIRTUALIZED"
    title: Object Storage-Tier
    description: Choose Object Storage-Tier
    enum:
          - "PARAVIRTUALIZED"
          - "ISCSI"

  firmware:
    type: string
    required: true
    visible: true
    default: "UEFI_64"
    title: Firmware
    description: Firmware


  
  network_type:
    type: enum
    required: false
    visible: true
    default: "PARAVIRTUALIZED"
    title: Network Type
    description: Choose Network Type
    enum:
          - "PARAVIRTUALIZED"
          - "ISCSI"
  
  remote_data_volume_type:
    type: enum
    required: false
    visible: true
    default: "PARAVIRTUALIZED"
    title: Remote Data Volume Type
    description: Choose Remote Data Volume Type
    enum:
          - "PARAVIRTUALIZED"
          - "ISCSI"

  ssh_authorized_keys:
    type: string
    required: true
    visible: true
    title: Ssh authorized keys
    description: Paste ssh authorized keys for VM

  vm_shape:
    type: string
    required: true
    visible: true
    default: "VM.Standard.E4.Flex"
    title: VM shape
    description: Select VM shape
  
  memory_in_gbs:
    type: string
    required: true
    visible: true
    title: Memory in gbs
    description: Select Memory in gbs for VM

  ocpu_count: 
    type: string
    required: true
    visible: true
    title: OCPU count for VM
    description: Select Ocpu count for VM
  
 

### END