title: Public IP pool
description: Public IP pool
schemaVersion: 1.1.0
version: "05072023"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Select the target compartment to create the resources"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_name}
      - ${compartment_id_in_subtree}
      - ${byoip_range_ocid}
      - ${public_ip_pool_cidr_block}
      - ${project_tag}
      - ${public_ip_pool_display_name}

variables:

####################################
#  Common Compartment
####################################

  compartment_name:
    type: string
    title: "Compartment Name"
    default: ""
    description: "Provide Compartment name"
    visible: true
    required: true

  compartment_id_in_subtree:
    type: bool
    title: "Compartment ID in Subtree"
    default: true
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  tenancy_ocid:
    visible: true
    required: true
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    required: true
    title: Enter the Region
    description: Enter the Region

  project_tag:
    type: oci:identity:tag:value
    title: "Attach Tags"
    description: "Attach the Tags"
    visible: true
    required: true
  
  byoip_range_ocid:
    type: string
    required: true
    visible: true
    default: ""
    title: "BYOIP Range ID"
    description: "Enter your BYOIP Range ID here"

  public_ip_pool_cidr_block:
    type: string
    required: true
    visible: true
    default: "10.0.0.0/24"
    title: "Pubic IP pool CIDR Block"
    description: "Enter the CIDR Block Range here"

  public_ip_pool_display_name:
    type: string
    required: true
    visible: true
    default: "My_IP_Pool"
    title: "Name of public IP pool"
    description: "Enter the Name of public IP pool"
  