
# On pull request events, this workflow will run
# `terraform init`, and `terraform plan`. On successful pull request merge, `terraform apply` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Deploy Block_Storage_Block_Volume'
on:
  pull_request:
    types: [opened, closed]
    branches:
      - 'dev4'
    paths:
      - 'terraform_CICD_v1.3/stack04_storage/01.block_storage_block_volume/*'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  stack04_Block_Storage_Block_Volume:
    uses: ./.github/workflows_1.3/action_runner.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "oci_github"
      BRANCH_NAME: "feature_stack04_storage"
      STACK_NAME: "stack04_block_storage_block_volume"
      WORKING_DIRECTORY: "terraform_CICD_v1.3/stack04_storage/01.block_storage_block_volume"
      REPO_URL: "https://github.com/ebizon-cloud/oci_automation.git"
      TF_VERSION: "1.2.x"

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
