
# On pull request events, this workflow will run
# `terraform init`, and `terraform plan`. On successful pull request merge, `terraform apply` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Deploy Exadata VM Clusters'
on:
  pull_request:
    types: [opened, closed]
    branches:
      - 'dev5'
    paths:
      - 'terraform_CICD_v1.3/stack05_oracledb/05.exadata_vm_clusters/*'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  stack05_exadata_vm_clusters:
    uses: ./.github/workflows_1.3/action_runner.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "oci_github"
      BRANCH_NAME: "feature_stack05_oracledb"
      STACK_NAME: "stack05_exadata_vm_clusters"
      WORKING_DIRECTORY: "terraform_CICD_v1.3/stack05_oracledb/05.exadata_vm_clusters"
      REPO_URL: "https://github.com/ebizon-cloud/oci_automation.git"
      TF_VERSION: "1.2.x"

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
