title: Create private endpoint
description: Private endpoint Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"

#####################################
# Variable Groupings
#####################################

groupings:
 
 
  - title: "private endpoint Configuration"
    variables:
      - ${private_endpoint_display_name}
      - ${private_endpoint_is_used_with_configuration_source_provider}
      - ${subnet_display_name}
      - ${vcn_display_name}

  - title: "Select Compartment"
    variables:
      - ${app_compartment_name}
      - ${app_compartment_id_in_subtree}
      - ${network_compartment_name}
      - ${network_compartment_id_in_subtree}
      - ${tenancy_ocid}
      - ${region}
      - ${availability_domain}


#####################################
# Common variables
#####################################

variables:

  app_compartment_name:
    type: string
    visible: true
    title: Compartment Name
    description: Compartment Name of the Resource
    default: ""
    required: true

  app_compartment_id_in_subtree:
    type: boolean
    visible: true
    title: Compartment ID in Subtree
    description: Compartment ID in Subtree
    default: true
    required: true

  network_compartment_name:
    type: string
    visible: true
    title: Compartment Name
    description: Compartment Name of the Resource
    default: ""
    required: true

  network_compartment_id_in_subtree:
    type: boolean
    visible: true
    title: Compartment ID in Subtree
    description: Compartment ID in Subtree
    default: true
    required: true

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Tenancy OCID
    required: true

  region:
    visible: false
    title: Region
    description: Region
    required: true
 
  availability_domain:
    type: oci:identity:availabilitydomain:name
    visible: true
    title: Select the availability domain to deploy resources
    description: Choose the availability domain to deploy the resources
    dependsOn: 
      compartmentId: ${compartment_ocid}   
      
#####################################
# private end point variables
#####################################

  private_endpoint_display_name:
    type: string
    required: true
    visible: true
    default: "private_endpoint"
    title: "Private endpoint name"
    description: "Choose private endpoint name"
  
  private_endpoint_is_used_with_configuration_source_provider:
    type: boolean
    required: true
    title: Auto-tune performance is enabled
    visible: true
    description: Whether the private endpoint is used with configuration source provider     
    default: false

  subnet_display_name:
    type: string
    required: true
    visible: true
    default: ""
    title: "Subnet Name"
    description: "Subnet Name"

  vcn_display_name:
    type: string
    required: true
    visible: true
    default: ""
    title: "VCN Name"
    description: "VCN Name"        

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false
