variable "source_database_connection_ocid" {}
variable "target_database_connection_ocid" {}
variable "migration_type" {}
variable "migration_data_transfer_medium_details_database_link_details_wallet_bucket_bucket" {}
variable "migration_data_transfer_medium_details_database_link_details_wallet_bucket_namespace" {}
variable "migration_data_transfer_medium_details_object_storage_details_bucket" {}
variable "migration_data_transfer_medium_details_object_storage_details_namespace" {}
variable "migration_datapump_settings_export_directory_object_name" {}
variable "migration_datapump_settings_import_directory_object_name" {}
variable "migration_datapump_settings_metadata_remaps_new_value" {}
variable "migration_datapump_settings_metadata_remaps_old_value" {}
variable "migration_datapump_settings_metadata_remaps_type" {}
variable "migration_dump_transfer_details_source_kind" {}
variable "migration_dump_transfer_details_target_kind" {}
variable "migration_exclude_objects_object" {}
variable "migration_exclude_objects_owner" {}
variable "migration_golden_gate_details_hub_rest_admin_credentials_password" {}
variable "migration_golden_gate_details_hub_rest_admin_credentials_username" {}
variable "migration_golden_gate_details_hub_source_db_admin_credentials_password" {}
variable "migration_golden_gate_details_hub_source_db_admin_credentials_username" {}
variable "source_microservices_deployment_name" {}
variable "migration_golden_gate_details_hub_target_db_admin_credentials_password" {}
variable "migration_golden_gate_details_hub_target_db_admin_credentials_username" {}
variable "target_microservices_deployment_name" {}
variable "migration_golden_gate_details_hub_url" {}
variable "migration_golden_gate_details_hub_source_container_db_admin_credentials_password" {}
variable "migration_golden_gate_details_hub_source_container_db_admin_credentials_username" {}
variable "migration_include_objects_object" {}
variable "migration_include_objects_owner" {}
variable "compartment_ocid" {}
variable "test_key_ocid" {}
variable "test_vault_ocid" {}
