    # tenancy_ocid                         = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
    # region                               = "us-ashburn-1"
    # monitoring_compartment_name          = "oci_monitoring" 
    # app_compartment_name                 = "oci_nonprod_app" 
    # log_analytics_log_group_display_name = "Example_group" 