title: Deploy Environment
description: Deploy Environment
schemaVersion: 1.1.0
version: "12072023"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Select Compartment"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_name}
      - ${compartment_id_in_subtree} 
      - ${project_tag}
      - ${deploy_environment_type}
      - ${function_id}
      - ${deploy_environment_display_name}
      - ${project_name}
      - ${notification_topic}
      
variables:


#####################################
# Common Variables
#####################################

  compartment_name:
    type: string
    visible: true
    title: Compartment Name
    description: Compartment Name of the Resource
    default: ""

  compartment_id_in_subtree:
    type: boolean
    visible: true
    title: Compartment ID in Subtree
    description: Compartment ID in Subtree
    default: true

  region:
    visible: false
    required: true
    title: Region
    description: Enter Region
    default: "us-ashburn-1"

  tenancy_ocid:
    title: "Tenancy OCID"
    type: string
    required: true 

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

#####################################
# Dev environment Variables
#####################################

  deploy_environment_type:
    type: string
    visible: true
    required: true
    title: Deploy Environment Type
    description: "Deployment environment type"
    default: "FUNCTION"

  function_id:
    type: string
    visible: true
    required: true
    title: Function OCID
    default: "defaultValue"
  
  deploy_environment_display_name:
    type: string
    visible: true
    required: true
    title: Deploy Environment Display Name
    description: "Deployment environment display name."
    default: "test_deploy_environment"
  
  project_name:
    type: string
    visible: true
    required: true
    title: Project Name
    description: "Provide the Project name "
    default: "build_project"

  notification_topic:
    type: string
    visible: true
    required: true
    title: Notification Topic Name
    description: "Provide name for Notification Topic"
    default: "test_topic001"
