title: OCI Core Custom Images
description: OCI Core Custom Images 
schemaVersion: 1.1.0
version: "08062023"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Select Compartment "
    variables:
      - ${region}
      - ${tenancy_ocid}
      - ${app_compartment_id_in_subtree}
      - ${app_compartment_name}
      - ${project_tag}
      - ${instances_display_name}
      
 
  - title: "Select custom image variables"
    variables:
      - ${instance_ocid}
      - ${launch_mode}
      - ${image_timeout_create}


variables:
######################
### Common Compartment 
######################

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Enter Tenancy OCID

  region:
    visible: true
    title: Region
    description: Enter Region
    default: "us-ashburn-1"
    
  app_compartment_id_in_subtree:
    type: bool
    title: "Compartment ID in Subtree"
    default: true
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  app_compartment_name:
    type: string
    title: "Compartment Name"
    default: ""
    description: "Compartment Name to deploy the resource"
    visible: true
    required: true

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false
    
##########################
### Custom image variables
##########################

  launch_mode:
    type: string
    visible: true
    required: true
    title: lauch mode
    default: "NATIVE"
    description: instance launch mode

  instances_display_name:
    type: string
    visible: true
    required: true
    title: instance Name
    default: ""
    description: instance Name  

  image_timeout_create:
    type: string
    visible: true
    required: true
    title: create timeout
    default: "30m"
    description: create timeout