    tenancy_ocid        = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
    region              = "us-ashburn-1" 
    compartment_name    = "oci_security" 
    vault_display_name  = "oci_KMS-VAULT" 
    master_display_name = "Oke_key" 