title:  Create Data Integration Workspace
description: Data Integration Workspace
schemaVersion: 1.1.0
version: "25012022"
#####################################
# Variable Groupings
#####################################
groupings:

  - title: "Select Compartment"
    variables:
      - ${compartment_ocid}
      - ${region}

  - title: "Data_integration_Workspace"
    variables:
      - ${description}
      - ${display_name}
      - ${is_private_network_enabled}
     
variables:
#####################################
# Common Compartment
#####################################  
  
  compartment_ocid:
    type: oci:identity:compartment:id
    visible: true
    title: Select the Compartment to deploy resources
    description: Choose the Compartment where to deploy the resources

  region:
    visible: true
    title: Region name
    description: Region name

######################################
# log_analytics_entity
######################################

  description:
    type: string
    default: "Data_integration_Workspace_Example"
    title: "Data Integration Workspace description details"
    required: true
    visible: true

  display_name:
    type: string
    default: "Workspace_Example"
    title: "Workspace display name"
    description: "Workspace display name"
    required: true
    visible: true

  is_private_network_enabled:
    type: bool
    default: false
    title: "Is Private Network Enabled?"
    required: true
    visible: true
 
