title: OKE Terraform Input Variables
description: OKE Terraform Input Variables
schemaVersion: 1.1.0
version: "26102022"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "OKE Cluster Variables"
    variables:
      - ${create_private_k8s_endpoint}
      - ${oke_display_name}
      - ${instance_vm_image_ocid}
      - ${node_pool_node_source_details_boot_volume_size_in_gbs}
      - ${node_pool_count}
      - ${node_pool_regional_size}
      - ${node_instance_shape}
      - ${node_config_memory_in_gbs}
      - ${node_config_ocpus}
      - ${use_custom_ssh_public_key}
      - ${ssh_public_key}


  - title: "OKE Network Configuration"
    variables:
      - ${pod_network_option_details_cni_type}
      - ${pod_network_option_details_max_pods_per_node}
      - ${k8s_cluster_pods_cidr_blocks}
      - ${k8s_cluster_services_cidr_blocks}
      - ${pod_network_option_details_pod_subnet_ids}
      - ${pod_network_option_details_pod_nsg_ids}
      

  - title: "Select Compartment"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${project_tag}
      - ${app_compartment_id_in_subtree}
      - ${oke_compartment_name}
      - ${network_compartment_id_in_subtree}
      - ${network_compartment_name}
      - ${k8s_api_endpoint_subnet_display_name}
      - ${worker_subnet_display_name}
      - ${load_balancer_subnet_display_name}
      - ${vcn_display_name}

variables:

#####################################
# Common variables
#####################################
  

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    title: Region
    description: Region

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

  app_compartment_id_in_subtree:
    type: bool
    default: true
    title: "Compartment id in subtree"
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  oke_compartment_name:
    type: string
    default: ""
    title: "Compartment Name to deploy the resource"
    description: "Compartment Name to deploy the resource"
    visible: true
    required: true
  
  network_compartment_id_in_subtree:
    type: bool
    default: true
    title: "Compartment id in subtree"
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  network_compartment_name:
    type: string
    default: ""
    title: "Compartment Name of the Subnet and Vcn"
    description: "Compartment Name of the Subnet"
    visible: true
    required: true

  k8s_api_endpoint_subnet_display_name:
    type: string
    default: ""
    title: "k8s_api_endpoint_subnet_display_name"
    description: "The subnet in which the application is deployed"
    visible: true
    required: true
  
  worker_subnet_display_name:
    type: string
    default: ""
    title: "worker_subnet_display_name"
    description: "The subnet in which the application is deployed"
    visible: true
    required: true

  load_balancer_subnet_display_name:
    type: string
    default: ""
    title: "load_balancer_subnet_display_name"
    description: "The subnet in which the application is deployed"
    visible: true
    required: true
  
  vcn_display_name:
    type: string
    default: ""
    title: "VCN Name"
    description: "The Vcn in which the application is deployed"
    visible: true
    required: true


######################################
# Core OKE variables
######################################

  oke_display_name:
    type: string
    title: OKE Display Name
    description: Provide custom display name for Core Kubernetes Cluster
    visible: true
    required: true
    default: "Example_oke"

  create_private_k8s_endpoint:
    type: boolean
    title: Create Private OKE Cluster ?
    description: Whether the cluster should be assigned a public IP address, If it is unchecked PUBLIC endpoint will be created
    visible: true
    required: true
    default: true

  use_custom_ssh_public_key:
    type: boolean
    title: Use Custom SSH Public Key for Worker Nodes ?
    description: IF you choose this, you will be asked to provide the SSH public key, If Unchecked terraform will generate one.
    default: false
    required: true

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: Provide the SSH Public Key for Worker Nodes
    visible: ${use_custom_ssh_public_key}
    required: true

  node_instance_shape:
    type: oci:core:instanceshape:name
    title: OKE Cluster Worker Node Shape
    description: OKE Cluster Worker Node Shape
    visible: true
    required: true
    default: "VM.Optimized3.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  node_config_memory_in_gbs:
    type: number
    title: OKE Cluster Worker Node Memory Size in GB
    description: OKE Cluster Worker Node Memory Size in GB
    minimum: 1
    visible:
      or:
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Optimized3.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard.E3.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.DenseIO.E4.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard.A1.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard.E4.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard3.Flex
    required: true
    default: 4

  node_config_ocpus:
    type: number
    title: OKE Cluster Worker Node OCPU Count
    description: OKE Cluster Worker Node OCPU Count
    minimum: 1
    visible:
      or:
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Optimized3.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard.E3.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.DenseIO.E4.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard.A1.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard.E4.Flex
        - and:
          - eq:
            - ${node_instance_shape}
            - VM.Standard3.Flex
    required: true
    default: 1

  instance_vm_image_ocid:
    type: string
    title: OKE Cluster Worker Node Image OCID 
    description: OKE Cluster Worker Node Image OCID, Worker Nodes created by this OKE cluster will use this image
    visible: true
    required: true
    default: "ocid1.image.oc1.iad.aaaaaaaamoajldhwrmbzx7s4xnrajj5b7nfrnutuebgwne4bxc7vpiap3gga"

  node_pool_node_source_details_boot_volume_size_in_gbs:
    type: number
    title: Worker Node Boot Volume Size in GB
    description: Boot Volume Size in GB, Minimum 50 GB is required
    visible: true
    required: true
    default: "50"
    minimum: 50

  node_pool_count:
    type: number
    title: Number of Node Pools to create for OKE Cluster
    description: Each node pool will be created with the number of worker nodes you specify
    visible: true
    required: true
    default: 1
    minimum: 1

  node_pool_regional_size:
    type: number
    title: Number of Worker Nodes to create for OKE Cluster
    description: Each node pool will be created with the number of worker nodes you specify
    visible: true
    required: true
    default: 1
    minimum: 1


#####################################
# Network Configuration
#####################################

  pod_network_option_details_cni_type:
    type: enum
    title: OKE Cluster Container Networking Type
    description: Select the CNI Plugin
    visible: true
    required: true
    default: OCI_VCN_IP_NATIVE
    enum:
      - OCI_VCN_IP_NATIVE
      - FLANNEL_OVERLAY

  pod_network_option_details_max_pods_per_node:
    type: number
    title: Provide Maximum Number of Pods can be deployed to each worker node
    description: The max number of pods per node in the node pool. This value will be limited by the number of VNICs attachable to the node pool shape
    required: false
    default: 110
    visible:
      not:
        - eq:
            - ${pod_network_option_details_cni_type}
            - FLANNEL_OVERLAY

  k8s_cluster_pods_cidr_blocks:
    type: string
    title: OKE Cluster Pods CIDR Block
    visible:
      and:
        - eq:
            - ${pod_network_option_details_cni_type}
            - FLANNEL_OVERLAY
    required: true
    default: "172.17.0.0/16"

  k8s_cluster_services_cidr_blocks:
    type: string
    title: OKE Cluster Services CIDR Block
    description: OKE Cluster Services CIDR Block
    visible:
      and:
        - eq:
            - ${pod_network_option_details_cni_type}
            - FLANNEL_OVERLAY
    required: true
    default: "172.16.0.0/16"


 