title: FastConnect
description: FastConnect Terraform Variables
schemaVersion: 1.1.0
version: "05102022"
variableGroups:

  - title: FastConnect Variables
    variables:
      - fastconnect_provider
      - virtual_circuit_display_name
      - virtual_circuit_bandwidth_shape
      - create_private_virtual_circuit
      - fastconnect_routing_policy
      - virtual_circuit_cross_connect_mappings_customer_bgp_peering_ip
      - virtual_circuit_cross_connect_mappings_oracle_bgp_peering_ip
      - virtual_circuit_cross_connect_mappings_customer_secondary_bgp_peering_ip
      - virtual_circuit_cross_connect_mappings_oracle_secondary_bgp_peering_ip
      - provider_service_key_name
      - virtual_circuit_customer_asn
      - use_bgp_md5_authentication_key
      - bgp_md5_authentication_key
      - drg_ocid

  - title: "Select the target compartment to create the resources"
    variables:
      - compartment_ocid
      - tenancy_ocid
      - region


variables:

#####################################

# Common Compartment

#####################################

  compartment_ocid:
    type: oci:identity:compartment:id
    visible: true
    title: Select the Target Compartment to deploy resources
    description: Choose the Compartment where to deploy the resources

  tenancy_ocid:
    visible: false
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    title: Region
    description: Region

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


#####################################

# FastConnect Variables

#####################################

  fastconnect_provider:
    type: enum
    description: "Available FastConnect providers: AT&T, Microsoft Azure, Megaport, QTS, CEintro, Cologix, CoreSite, Digitial Realty, EdgeConneX, Epsilon, Equinix, InterCloud, Lumen, Neutrona, OMCS, OracleL2ItegDeployment, OracleL3ItegDeployment, Orange, Verizon, Zayo, PacketFabric"
    enum:
      - AT&T
      - Microsoft Azure
      - Megaport
      - QTS
      - CEintro
      - Cologix
      - CoreSite
      - Digitial Realty
      - EdgeConneX
      - Epsilon
      - Equinix
      - InterCloud
      - Lumen
      - Neutrona
      - OMCS
      - OracleL2ItegDeployment
      - OracleL3ItegDeployment
      - Orange
      - Verizon
      - Zayo
      - PacketFabric
    default: Megaport
    visible: true
    required: true
    title: FastConnect Provider

  virtual_circuit_display_name:
    type: string
    description: Provide name for Fastconnect Virtual Circuit
    visible: true
    required: true
    title: FastConnect Virtual Circuit Display Name


  virtual_circuit_bandwidth_shape:
    type: enum
    description: The provisioned data rate of the connection. Choose between 1 or 10 for FastConnect partner. Or choose between 1, 10 or 100 for FastConnect Direct.
    enum:
      - 1
      - 10
      - 100
    visible: true
    required: true
    title: Virtual Circuit Bandwidth Shape

  create_private_virtual_circuit:
    type: boolean
    description: If it is Checked, PRIVATE Virtual Circuit will be created, if unchecked, PUBLIC Virtual Circuit will be created
    default: true
    visible: true
    required: true
    title: Create Private Virtual Circuit ?
  
  fastconnect_routing_policy:
    type: enum
    description: "Available FastConnect routing policies: ORACLE_SERVICE_NETWORK, REGIONAL, MARKET_LEVEL, GLOBAL"
    visible: 
      not:
        - ${create_private_virtual_circuit}
    required: true
    uniqueItems: true
    title: Select FastConnect Routing Policy
    enum:
      - ORACLE_SERVICE_NETWORK
      - REGIONAL
      - MARKET_LEVEL
      - GLOBAL
    default: "MARKET_LEVEL"

  virtual_circuit_cross_connect_mappings_customer_bgp_peering_ip:
    type: string
    description: This is the BGP IPv4 address of the customer's router. Provide IPv4 Address Example - 10.0.0.22/30, Enter Placeholder value for Non-ASN Virtual Circuits.
    visible: ${create_private_virtual_circuit}
    required: true
    title: Virtual Circuit Cross Connect Mappings - Customer BGP peering IP
    default: ""
  
  virtual_circuit_cross_connect_mappings_oracle_bgp_peering_ip:
    type: string
    description: IPv4 address for Oracle's end of the BGP session. Provide IPv4 Address Example - 10.0.0.21/30, Enter Placeholder value for Non-ASN Virtual Circuits.
    visible: ${create_private_virtual_circuit}
    required: true
    title: Virtual Circuit Cross Connect Mappings - Oracle BGP Peering IP
    default: ""
  
  provider_service_key_name:
    type: string
    description: The provider service key that the provider gives you when you set up a virtual circuit connection from the provider to OCI
    visible:
      and:
        - eq:
            - ${fastconnect_provider}
            - Microsoft Azure
    required: true
    title: Provider Service Key Name
  
  virtual_circuit_cross_connect_mappings_customer_secondary_bgp_peering_ip:
    type: string
    description: This is the secondary BGP IPv4 address of the customer's router
    visible:
      and:
        - eq:
            - ${fastconnect_provider}
            - Microsoft Azure
    required: true
    title: Virtual Circuit Cross Connect Mappings - Customer Secondary BGP Peering IP
  
  virtual_circuit_cross_connect_mappings_oracle_secondary_bgp_peering_ip:
    type: string
    description: Secondary IPv4 address for Oracle's end of the BGP session
    visible:
      and:
        - eq:
            - ${fastconnect_provider}
            - Microsoft Azure
    required: true
    title: Virtual Circuit Cross Connect Mappings - Oracle Secondary BGP Peering IP
  
  virtual_circuit_customer_asn:
    type: string
    description: The BGP ASN of the network at the other end of the BGP session from Oracle. Enter Placeholder value for Non-ASN Virtual Circuits.
    visible:
      and:
        - not:
            - eq:
                - ${fastconnect_provider}
                - Microsoft Azure
    required: true
    pattern: "^[0-9]"
    title: Customer BGP ASN
    default: "123456"

  use_bgp_md5_authentication_key:
    type: boolean
    description: Provide a key only if your system requires MD5 authentication.
    visible: true
    title: Use a BGP MD5 Authentication Key
    required: true

  bgp_md5_authentication_key:
    type: string
    description: Enter a BGP MD5 authentication key
    visible: use_bgp_md5_authentication_key
    title: BGP MD5 Authentication Key
    required: true


  drg_ocid:
    type: string
    visible: ${create_private_virtual_circuit}
    required: true
    title:  DRG (Dynamic Routing Gateway) OCID
    description: This DRG will be connected to FastConnect Virtual Circuit

