title: Create CA Bundle
description: CA Bundle Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"
#####################################
# Variable Groupings
#####################################
groupings:

  - title: "OCI_Certificates_Management_CA_Bundle"
    variables:
      # - ${compartment_ocid}
      - ${region}
      - ${tenancy_ocid}
      - ${project_tag}
      - ${compartment_id_in_subtree}
      - ${compartment_name}
      - ${ca_bundle_ca_bundle_pem}
      - ${description}
      - ${ca_bundle_name}
      
variables:
#####################################
# oci certificates management ca bundle
#####################################

  # compartment_ocid:
  #   type: oci:identity:compartment:id
  #   visible: true
  #   title: "Select the Compartment to deploy resources"
  #   description: "The OCID of the compartment"

  region:
    visible: true
    title: "Region"
    description: "The region where the resources will be provisioned"

  tenancy_ocid:
    visible: true
    title: "Tenancy OCID"
    description: "Tenancy OCID"

  compartment_name:
    type: string
    title: "Compartment Name"
    default: ""
    description: "Provide Compartment name"
    visible: true
    required: true

  compartment_id_in_subtree:
    type: bool
    title: "Compartment ID in Subtree"
    default: true
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  project_tag:
    type: oci:identity:tag:value
    title: "Attach Tags"
    description: "Attach the Tags"
    visible: true
    required: false

  ca_bundle_ca_bundle_pem:
    type: string
    default: ""
    title: "CA Bundle PEM"
    description: "The PEM-encoded certificate bundle to be uploaded"
    required: true
    visible: true

  description:
    type: string
    default: "Demo"
    title: "CA Bundle Description"
    description: "A description for the CA Bundle"
    required: true
    visible: true

  ca_bundle_name:
    type: string
    default: "MyCAbundle"
    title: "CA Bundle Name"
    description: "The name of the CA bundle"
    required: true
    visible: true
  