title: Create Certificate Authority
description: Certificate Authority Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"
#####################################
# Variable Groupings
#####################################
groupings:

  - title: "oci_certificates_management_certificate_authority"
    variables:
      - ${compartment_id_in_subtree}
      - ${compartment_name}
      - ${region}
      - ${tenancy_ocid}
      - ${project_tag}
      - ${certificate_authority_certificate_authority_config_config_type}
      - ${certificate_authority_certificate_authority_config_signing_algorithm}
      - ${certificate_authority_certificate_authority_config_validity_time_of_validity_not_after}
      - ${certificate_authority_certificate_authority_config_validity_time_of_validity_not_before}
      - ${certificate_authority_certificate_authority_config_version_name}
      - ${certificate_authority_name}
      - ${certificate_authority_certificate_authority_rules_rule_type}
      - ${certificate_authority_certificate_authority_rules_certificate_authority_max_validity_duration}
      - ${certificate_authority_certificate_authority_rules_leaf_certificate_max_validity_duration}
      - ${certificate_authority_certificate_revocation_list_details_object_storage_config_object_storage_object_name_format}
      - ${certificate_authority_description}
      - ${key_management_endpoint}
      - ${certificate_authority_certificate_authority_config_subject_common_name}
      - ${object_storage_bucket_name}
      
variables:
#####################################
# oci certificates management certificate authority
#####################################

  region:
    visible: true
    title: "Region"
    description: "The region where the resources will be provisioned."
  
  tenancy_ocid:
    type: string
    default: ""
    title: "Tenancy OCID"
    description: "Tenancy OCID"
    visible: true
    required: true

  compartment_id_in_subtree:
    type: bool
    default: true
    title: "Compartment id in subtree"
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  compartment_name:
    type: string
    default: ""
    title: "Compartment Name to deploy the resource"
    description: "Compartment Name to deploy the resource"
    visible: true
    required: true

  key_management_endpoint:
    type: string
    default: ""
    title: "Management end point Name"
    description: "Management end point Name"
    required: true
    visible: true

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false
  
  certificate_authority_certificate_authority_config_config_type:
    type: string
    default: "ROOT_CA_GENERATED_INTERNALLY"
    title: "Configuration Type"
    description: "The configuration type for the certificate authority"
    required: true
    visible: true

  certificate_authority_certificate_authority_config_signing_algorithm:
    type: string
    default: "SHA256_WITH_RSA"
    title: "Signing Algorithm"
    description: "The signing algorithm to be used by the certificate authority"
    required: true
    visible: true

  certificate_authority_certificate_authority_config_validity_time_of_validity_not_after:
    type: string
    default: "2024-07-05T21:10:29.999Z"
    title: "Time of validity (not after)"
    description: "The time of validity indicating when the certificate authority is no longer valid after."
    required: true
    visible: true

  certificate_authority_certificate_authority_config_validity_time_of_validity_not_before:
    type: string
    default: "2023-07-04T21:10:29.999Z"
    title: "Time of validity (not before)"
    description: "The time of validity indicating when the certificate authority becomes valid"
    required: true
    visible: true

  certificate_authority_certificate_authority_config_version_name:
    type: string
    default: "versionName"
    title: "CA configuration version name"
    description: "The version name for the certificate authority configuration"
    required: true
    visible: true

  certificate_authority_name:
    type: string
    default: "Sample_CA"
    title: "Certificate Authority name"
    description: "The name of the certificate authority"
    required: true
    visible: true

  certificate_authority_certificate_authority_rules_rule_type:
    type: string
    default: "CERTIFICATE_AUTHORITY_ISSUANCE_EXPIRY_RULE"
    title: "Rule Type"
    description: "The rule type for the certificate authority."
    required: true
    visible: true
    
  certificate_authority_certificate_authority_rules_certificate_authority_max_validity_duration:
    type: string
    default: "P3650D"
    title: "CA max validity duration"
    description: "The maximum validity duration for the certificate authority. "
    required: true
    visible: true

  certificate_authority_certificate_authority_rules_leaf_certificate_max_validity_duration:
    type: string
    default: "P30D"
    title: "Leaf certificate max validity duration"
    description: "The maximum validity duration for leaf certificates issued by the certificate authority."
    required: true
    visible: true

  certificate_authority_certificate_revocation_list_details_object_storage_config_object_storage_object_name_format:
    type        : string
    default     : "ca-1-crl"
    title : "Object name format"
    description: "The object name format for the certificate revocation list stored in Object Storage."
    required: true
    visible: true

  certificate_authority_description:
    type: string
    default: "My Example CA"
    title: "Certificate authority description"
    description: "A description of the certificate authority."
    required: true
    visible: true 

  certificate_authority_certificate_authority_config_subject_common_name:
    type: string
    default: "www.example.com"
    title: "Common name"
    description: "The common name to be used in the subject of the certificate authority."
    required: true
    visible: true

  object_storage_bucket_name:
    type: string
    default: "ca-crl-bucket"
    title: "Object Storage Bucket name"
    description: "The name of the Object Storage bucket where the CA Certificate Revocation List (CRL) will be stored"
    required: true
    visible: true