title:  Create log analytics entity
description: Log analytics entity
schemaVersion: 1.1.0
version: "25012022"
#####################################
# Variable Groupings
#####################################
groupings:

  - title: "Select Compartment"
    variables:
      
      - ${tenancy_ocid}
      - ${monitoring_compartment_name}
      - ${monitoring_compartment_id_in_subtree}
      - ${app_compartment_name}
      - ${app_compartment_id_in_subtree}
      - ${region}
      - ${project_tag}


  - title: "log_analytics_entity"
    variables:
      - ${log_analytics_entity_entity_type_name}
      - ${log_analytics_entity_name}
      - ${log_analytics_entity_hostname}

variables:
#####################################
# Common Compartment
#####################################  
  tenancy_ocid:
    visible: true
    required: true
    title: Tenancy OCID
    description: Tenancy OCID

  monitoring_compartment_name:
    type: string
    title: "Compartment Name"
    default: ""
    description: "Provide Compartment name"
    visible: true
    required: true

  monitoring_compartment_id_in_subtree:
    type: bool
    title: "Compartment ID in Subtree"
    default: true
    description: "Compartment ID in Subtree"
    visible: true
    required: true

  app_compartment_name:
    type: string
    title: "Compartment Name"
    default: ""
    description: "Provide Compartment name"
    visible: true
    required: true

  app_compartment_id_in_subtree:
    type: bool
    title: "Compartment ID in Subtree"
    default: true
    description: "Compartment ID in Subtree"
    visible: true
    required: true
  
  region:
    visible: true
    required: true
    title: Region
    description: Region

######################################
# log_analytics_entity
######################################

  log_analytics_entity_entity_type_name:
    type: string
    default: "Host (Linux)"
    title: "entity type name"
    description: "type name"
    required: true
    visible: true

  log_analytics_entity_name:
    type: string
    default: "Example_entity"
    title: "log_analytics_entity_name"
    description: "Entity name"
    required: true
    visible: true
  
  log_analytics_entity_hostname:
    type: string
    default: "aa.domainname.com"
    title: "log_analytics_entity_hostname"
    description: "Host name"
    required: true
    visible: true

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: true





   