tenancy_ocid             = "ocid1.tenancy.oc1..aaaaaaaaixdndclpk6ks2so5vdaca4q5efbz2rfxwlmy3djqlb46f6qo7xla"
region                   = "us-ashburn-1"
monitor_compartment_name = "monitoring"
network_compartment_name = "network"
subnet_display_name      = "prod_trust_subnet"