
# On pull request events, this workflow will run
# `terraform init`, and `terraform plan`. On successful pull request merge, `terraform apply` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Deploy ip_mgmt_public_ip_pool'
on:
  pull_request:
    types: [opened, closed]
    branches:
      - 'dev2'
    paths:
      - 'CICD/stack02_networking/16.ip_management_public_ip_pool/*'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  stack02_ip_mgmt_public_ip_pool:
    uses: ./.github/workflows/action_runner.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "oci_github"
      BRANCH_NAME: "feature_stack02_networking"
      STACK_NAME: "stack02_ip_mgmt_public_ip_pool"
      WORKING_DIRECTORY: "CICD/stack02_networking/16.ip_management_public_ip_pool"
      REPO_URL: "https://github.com/ebizon-cloud/oci_automation.git"
      TF_VERSION: "1.2.x"

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
