
# On pull request events, this workflow will run
# `terraform init`, and `terraform plan`. On successful pull request merge, `terraform apply` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Deploy AutoScaling_Configurations'
on:
  pull_request:
    types: [opened, closed]
    branches:
      - 'dev03'
    paths:
      - 'CICD/stack03_compute/07.autoscaling_configuration/*'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  stack03_autoscaling_configs:
    uses: ./.github/workflows/action_runner.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "oci_github"
      BRANCH_NAME: "feature_stack03_compute"
      STACK_NAME: "stack03_autoscaling_configs"
      WORKING_DIRECTORY: "CICD/stack_03_compute/07.autoscaling_configuration"
      REPO_URL: "https://github.com/ebizon-cloud/oci_automation.git"
      TF_VERSION: "1.2.x"

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
