
# On successful pull request merge, `terraform destroy` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Destroy Logging '
on:
  pull_request:
    types: [closed]
    branches:
      - 'dev9'
    paths:
      - '.github/workflows/09_1.logging_destroy_destroy.yaml'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  stack09_logging_destroy:
    uses: ./.github/workflows/action_runner_destroy.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "oci_github"
      BRANCH_NAME: "feature_stack09_observability_destroy"
      STACK_NAME: "stack9_logging_destroy"
      WORKING_DIRECTORY: "CICD/stack09_observability/01.logging"
      REPO_URL: "https://github.com/ebizon-cloud/oci_automation.git"
      TF_VERSION: "1.2.x"

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
