
# On pull request events, this workflow will run
# `terraform init`, and `terraform plan`. On successful pull request merge, `terraform apply` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Deploy vcn_prod'
on:
  repository_dispatch:
    types: [create-vcn]
  # pull_request:
  #   types: [opened]
  #   branches:
  #     - 'dev'
    # paths:
    #   - 'CICD/stack02_networking/03.vcn_prod/*'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  stack02_vcn_prod_ai_agent:
    uses: ./.github/workflows/ai_agent_action_runner_temporary.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "ai_agent_github_cicd"
      BRANCH_NAME: "dev"
      STACK_NAME: "stack02-ai-agent-${{ github.event.client_payload.stack_name }}"
      WORKING_DIRECTORY: "${{ github.event.client_payload.working_directory }}"
      REPO_URL: "https://github.com/kirankumar-badiger/oci_automation.git"
      TF_VERSION: "1.2.x"
      # TF_JSON: ${{ github.event.inputs.client_payload }}

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
