
# On pull request events, this workflow will run
# `terraform init`, and `terraform plan`. On successful pull request merge, `terraform apply` will be executed.
# Update PROVIDER_NAME, BRANCH_NAME, STACK_NAME, WORKING_DIRECTORY, REPO_URL, TF_VERSION

name: 'Deploy OIC Stack'
on:
  repository_dispatch:
    types: [ deploy-oic-stack ]
  # pull_request:
  #   types: [opened]
  #   branches:
  #     - 'dev'
    # paths:
    #   - 'CICD/stack02_networking/03.vcn_prod/*'

# ---------------------------------------------
# Permissions
# ---------------------------------------------

permissions:
  contents: write

jobs:
  
  ORM_STACK_TAGS:
    uses: ./.github/workflows/ai_agent_action_runner_v2.yaml

    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "ai_agent_github_cicd"
      BRANCH_NAME: "dev"
      STACK_NAME: "stack1_lz_defined_tags"
      WORKING_DIRECTORY: "terraform_lz/stack1/defined_tags"
      REPO_URL: "https://github.com/ebizon-cloud/generic-oic-automation.git"
      TF_VERSION: "1.2.x"
      # TF_VERSION: "1.2.x"
      # TF_JSON: ${{ github.event.inputs.client_payload }}

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
      PAT: ${{secrets.PAT}}


  ORM_STACK_COMPARTMENTS:
    uses: ./.github/workflows/ai_agent_action_runner_v2.yaml
    needs: ORM_STACK_TAGS
    # ---------------------------------------------
    # Source Provider Details
    # ---------------------------------------------

    with:

      PROVIDER_NAME: "ai_agent_github_cicd"
      BRANCH_NAME: "dev"
      STACK_NAME: "stack1_lz_compartments"
      WORKING_DIRECTORY: "terraform_lz/stack1/compartments"
      REPO_URL: "https://github.com/ebizon-cloud/generic-oic-automation.git"
      TF_VERSION: "1.2.x"
      # TF_VERSION: "1.2.x"
      # TF_JSON: ${{ github.event.inputs.client_payload }}

    # ---------------------------------------------
    # Secrets
    # ---------------------------------------------

    secrets:
      USER_OCID: ${{secrets.USER_OCID}}
      FINGERPRINT: ${{secrets.FINGERPRINT}}
      COMPARTMENT_OCID: ${{secrets.COMPARTMENT_OCID}}
      REGION: ${{secrets.REGION}}
      TENANCY_OCID: ${{secrets.TENANCY_OCID}}
      PRIVATE_KEY_FILE: ${{secrets.PRIVATE_KEY_FILE}}
      PAT: ${{secrets.PAT}}
