name: Encrypt Secret from Power Automate
on:
  repository_dispatch:
    types: [encrypt-secret]

jobs:
  encrypt-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install pynacl

      - name: Get public key
        id: get_key
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PUBLIC_KEY=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key \
            | jq -r .key)
          KEY_ID=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key \
            | jq -r .key_id)
          echo "public_key=$PUBLIC_KEY" >> $GITHUB_OUTPUT
          echo "key_id=$KEY_ID" >> $GITHUB_OUTPUT

      - name: Encrypt secret
        id: encrypt
        env:
          SECRET_VALUE: ${{ github.event.client_payload.secret_value }}
        run: |
          python - <<EOF
          from base64 import b64encode, b64decode
          from nacl import encoding, public
          import sys, json, os

          def encrypt(public_key: str, secret_value: str) -> str:
              """Encrypt a secret using libsodium"""
              public_key = b64decode(public_key)
              sealed_box = public.SealedBox(public.PublicKey(public_key))
              encrypted = sealed_box.encrypt(secret_value.encode("utf-8"))
              return b64encode(encrypted).decode("utf-8")

          # Encrypt the secret
          encrypted_value = encrypt(
              "${{ steps.get_key.outputs.public_key }}", 
              os.environ['SECRET_VALUE']
          )
          
          print(f"::set-output name=encrypted_value::{encrypted_value}")
          EOF

      - name: Create or update secret
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/${{ github.event.client_payload.secret_name }} \
            -d "{\"encrypted_value\":\"${{ steps.encrypt.outputs.encrypted_value }}\",\"key_id\":\"${{ steps.get_key.outputs.key_id }}\"}"
