name: Encrypt Secret from Power Automate
on:
  repository_dispatch:
    types: [encrypt-secret]

jobs:
  encrypt-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install pynacl

      - name: Get public key
        id: get_key
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/public-key)
          echo "public_key=$(echo $RESPONSE | jq -r .key)" >> $GITHUB_OUTPUT
          echo "key_id=$(echo $RESPONSE | jq -r .key_id)" >> $GITHUB_OUTPUT

      - name: Encrypt secret
        id: encrypt
        env:
          SECRET_VALUE: ${{ github.event.client_payload.secret_value }}
        run: |
          python - <<EOF
          from base64 import b64encode, b64decode
          from nacl import encoding, public
          import sys, json, os

          def encrypt(public_key: str, secret_value: str) -> str:
              """Encrypt a secret using libsodium"""
              try:
                  # Decode the public key from base64
                  public_key_bytes = b64decode(public_key.encode('utf-8'))
                  
                  # Create a sealed box with the public key
                  box = public.SealedBox(public.PublicKey(public_key_bytes))
                  
                  # Encrypt the secret value
                  encrypted = box.encrypt(secret_value.encode('utf-8'))
                  
                  # Return base64 encoded encrypted value
                  return b64encode(encrypted).decode('utf-8')
              except Exception as e:
                  print(f"Error during encryption: {str(e)}")
                  sys.exit(1)

          # Get the values from environment
          public_key = "${{ steps.get_key.outputs.public_key }}"
          secret_value = os.environ['SECRET_VALUE']

          # Encrypt and print the result
          encrypted_value = encrypt(public_key, secret_value)
          print(f"::set-output name=encrypted_value::{encrypted_value}")
          EOF

      - name: Create or update secret
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GH_TOKEN" \
            https://api.github.com/repos/${{ github.repository }}/actions/secrets/${{ github.event.client_payload.secret_name }} \
            -d "{\"encrypted_value\":\"${{ steps.encrypt.outputs.encrypted_value }}\",\"key_id\":\"${{ steps.get_key.outputs.key_id }}\"}"
