title:  Terraform Input Variables
description:  Terraform Input Variables
schemaVersion: 1.1.0
version: "25012022"

#####################################
# Variable Groupings
#####################################

groupings:

  - title: "Name for the compartment MUST be unique across all compartments in your tenancy"
    variables:
      - ${tenancy_ocid}
      - ${region}
      - ${compartment_ocid}
      - ${project_tag}

  - title: "1 Create prodhub compartment"
    variables:
      - ${prodhub_compartment_name}
      - ${prodhub_compartment_description}
      - ${prodhub_enable_delete}

  - title: "2 Create nonprodhub compartment"
    variables:
      - ${nonprodhub_compartment_name}
      - ${nonprodhub_compartment_description}
      - ${nonprodhub_enable_delete}    

  - title: "3 Create network compartment"
    variables:
      - ${network_compartment_name}
      - ${network_compartment_description}
      - ${network_enable_delete}

  - title: "4 Create monitoring compartment"
    variables:
      - ${monitoring_compartment_name}
      - ${monitoring_compartment_description}
      - ${monitoring_enable_delete}

  - title: "5 Create security compartment"
    variables:
      - ${security_compartment_name}
      - ${security_compartment_description}
      - ${security_enable_delete}

  - title: "6 Create nonprod compartment"
    variables:
      - ${nonprod_compartment_name}
      - ${nonprod_compartment_description}
      - ${nonprod_enable_delete}    
      - ${nonprod_project_tag}  

  - title: "6.1 Create nonprod/nonprod_dev sub-compartments"
    variables:
      - ${nonprod_dev_compartment_name}
      - ${nonprod_dev_compartment_description}
      - ${nonprod_dev_enable_delete}
      - ${nonprod_dev_project_tag}

  - title: "6.1.1 Create nonprod/nonprod_dev/appdev sub-compartments"
    variables:
      - ${appdev_compartment_name}
      - ${appdev_compartment_description}
      - ${appdev_enable_delete}
      - ${appdev_project_tag}

  - title: "6.1.2 Create nonprod/nonprod_dev/dbdev sub-compartments"
    variables:
      - ${dbdev_compartment_name}
      - ${dbdev_compartment_description} 
      - ${dbdev_enable_delete}
      - ${dbdev_project_tag}

  - title: "6.2 Create nonprod/nonprod_tst sub-compartments"
    variables:
      - ${nonprod_tst_compartment_name}
      - ${nonprod_tst_compartment_description}
      - ${nonprod_tst_enable_delete}
      - ${nonprod_tst_project_tag}

  - title: "6.2.1 Create nonprod/nonprod_tst/apptst sub-compartments"
    variables:
      - ${apptst_compartment_name}
      - ${apptst_compartment_description}
      - ${apptst_enable_delete}
      - ${apptst_project_tag}

  - title: "6.2.2 Create nonprod/nonprod_tst/dbtst sub-compartments"
    variables:
      - ${dbtst_compartment_name}
      - ${dbtst_compartment_description}   
      - ${dbtst_enable_delete}       
      - ${dbtst_project_tag}       

  - title: "7 Create prod compartment"
    variables:
      - ${prod_compartment_name}
      - ${prod_compartment_description}    
      - ${prod_enable_delete}
      - ${prod_project_tag}

  - title: "7.1 Create prod/app_prod sub-compartments"
    variables:
      - ${appprod_compartment_name}
      - ${appprod_compartment_description}
      - ${appprod_enable_delete}
      - ${appprod_project_tag}

  - title: "7.2 Create prod/db_prod sub-compartments"
    variables:
      - ${dbprod_compartment_name}
      - ${dbprod_compartment_description}    
      - ${dbprod_enable_delete} 
      - ${dbprod_project_tag} 

#####################################
# Common Compartment
#####################################
variables:

  tenancy_ocid:
    visible: true
    title: Tenancy OCID
    description: Tenancy OCID

  region:
    visible: true
    title: Region
    description: Region

  compartment_ocid:
    visible: true
    title: Provide the compartment_ocid for deployment
    description: Under this compartment all the resouces will be deployed

  project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false



### 1 Create prodhub compartment

  prodhub_compartment_name:
    type: string
    required: true
    visible: true
    default: "prod_hub"
    title: "compartment name"
    description: "Provide compartment Name"
   
  prodhub_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to prod_hub"
    title: "compartment description"
    description: "Provide compartment description."

  prodhub_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
    
### 2 Create nonprodhub compartment

  nonprodhub_compartment_name:
    type: string
    required: true
    visible: true
    default: "nonprod_hub"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprodhub_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod_hub"
    title: "compartment description"
    description: "Provide compartment description."  

  nonprodhub_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
    
### 3 Create network compartment

  network_compartment_name:
    type: string
    required: true
    visible: true
    default: "network"
    title: "compartment name"
    description: "Provide compartment Name"
   
  network_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to network"
    title: "compartment description"
    description: "Provide compartment description."

  network_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
   

### 4 Create monitoring compartment

  monitoring_compartment_name:
    type: string
    required: true
    visible: true
    default: "monitoring"
    title: "compartment name"
    description: "Provide compartment Name"
   
  monitoring_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to monitoring"
    title: "compartment description"
    description: "Provide compartment description."

  monitoring_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
    

### 5 Create security compartment

  security_compartment_name:
    type: string
    required: true
    visible: true
    default: "security"
    title: "compartment name"
    description: "Provide compartment Name"
   
  security_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to security"
    title: "compartment description"
    description: "Provide compartment description."

  security_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
    

### 6 Create nonprod compartment

  nonprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "nonprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod"
    title: "compartment description"
    description: "Provide compartment description."

  nonprod_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  nonprod_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 6.1 Create nonprod/nonprod_dev sub-compartments

  nonprod_dev_compartment_name:
    type: string
    required: true
    visible: true
    default: "nonprod_dev"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprod_dev_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod_dev"
    title: "compartment description"
    description: "Provide compartment description."

  nonprod_dev_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  nonprod_dev_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


 
### 6.1.1 Create nonprod/nonprod_dev/appdev sub-compartments

  appdev_compartment_name:
    type: string
    required: true
    visible: true
    default: "appdev"
    title: "compartment name"
    description: "Provide compartment Name"
   
  appdev_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to appdev"
    title: "compartment description"
    description: "Provide compartment description."
  
  appdev_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  appdev_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 6.1.2 Create nonprod/nonprod_dev/dbdev sub-compartments

  dbdev_compartment_name:
    type: string
    required: true
    visible: true
    default: "dbdev"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dbdev_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dbdev"
    title: "compartment description"
    description: "Provide compartment description."

  dbdev_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  dbdev_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


### 6.2 Create nonprod/nonprod_tst sub-compartments

  nonprod_tst_compartment_name:
    type: string
    required: true
    visible: true
    default: "nonprod_tst"
    title: "compartment name"
    description: "Provide compartment Name"
   
  nonprod_tst_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to nonprod_tst"
    title: "compartment description"
    description: "Provide compartment description."

  nonprod_tst_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  nonprod_tst_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 6.2.1 Create nonprod/nonprod_tst/apptst sub-compartments

  apptst_compartment_name:
    type: string
    required: true
    visible: true
    default: "apptst"
    title: "compartment name"
    description: "Provide compartment Name"
   
  apptst_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to apptst"
    title: "compartment description"
    description: "Provide compartment description."

  apptst_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  apptst_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

### 6.2.2 Create nonprod/nonprod_tst/dbtst sub-compartments

  dbtst_compartment_name:
    type: string
    required: true
    visible: true
    default: "dbtst"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dbtst_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dbtst"
    title: "compartment description"
    description: "Provide compartment description."

  dbtst_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  dbtst_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


### 7 Create prod compartment

  prod_compartment_name:
    type: string
    required: true
    visible: true
    default: "prod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  prod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to prod"
    title: "compartment description"
    description: "Provide compartment description."

  prod_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  prod_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


### 7.1 Create prod/app_prod sub-compartments

  appprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "appprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  appprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to appprod"
    title: "compartment description"
    description: "Provide compartment description."

  appprod_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  appprod_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false


### 7.2 Create prod/db_prod sub-compartments

  dbprod_compartment_name:
    type: string
    required: true
    visible: true
    default: "dbprod"
    title: "compartment name"
    description: "Provide compartment Name"
   
  dbprod_compartment_description:
    type: string
    required: true
    visible: true
    default: "Compartment for all resources related to dbprod"
    title: "compartment description"
    description: "Provide compartment description."

  dbprod_enable_delete:
    type: bool
    visible: true
    default: false
    title: "if unchecked, on `terraform destroy`, compartment is deleted from the terraform state but not from oci"
  
  dbprod_project_tag:
    type: oci:identity:tag:value
    title: Attach Tags
    description: Attach the Tags
    visible: true
    required: false

 ### END